Dev
Dreyrk/Yugioh-Project-Front pull request #1
Opened 2022-11-22 21:34 UTC by Dreyrk

2022-11-26 14:00 UTC, cyrheel requested changes

2022-11-26 14:00 UTC, cyrheel commented on src/App.css
>  .App {
move your css file into a Style folder (inside src folder oc)

2022-11-26 14:00 UTC, cyrheel commented on src/Pages/Home.jsx
> +      console.log(cardsData);
avoid console.log() except for console.log(error)

2022-11-26 14:00 UTC, cyrheel commented on src/components/Cards.jsx
> +      <CardBack></CardBack>
use syntaxt </> not <></>

2022-11-26 14:00 UTC, cyrheel commented on src/components/Header.jsx
> +      <NavLink to="/">
search for this : 

const navigate = useNavigate();

onClick() => navigate('/', {replace: true});

2022-11-26 14:00 UTC, cyrheel commented on src/index.css
>  body {
move css file into style folder

2022-11-26 15:46 UTC, Dreyrk commented on src/components/Cards.jsx
> +      <CardBack></CardBack>
i'm going to put children in

2022-12-02 19:13 UTC, cyrheel approved these changes

2022-12-02 19:20 UTC, merged