Pagination
Dreyrk/Yugioh-Project-Front pull request #3
Opened 2022-12-07 15:42 UTC by Dreyrk

2022-12-07 17:00 UTC, cyrheel commented on src/components/Cards.jsx
>    const filteredName = Name.replace(/\s*\(.*?\)\s*/g, "");
move this regex to the api

2022-12-07 17:01 UTC, cyrheel commented on src/components/Cards.jsx
> +    if (filteredRarity === "Commune") {
use switch statement

2022-12-07 17:02 UTC, cyrheel commented on src/components/Cards.jsx
> +  const images = rarityDefine(rarityNumber(Rarity.substring(9)));
make one big function who do the two, take a substring in params then in a switch create the array and return it

2022-12-07 17:02 UTC, cyrheel commented on src/components/Cards.jsx
>    const [isClicked, setIsClicked] = useState(false);
rename this var

2022-12-07 17:03 UTC, cyrheel commented on src/components/Cards.jsx
>    const filteredName = Name.replace(/\s*\(.*?\)\s*/g, "");
rename this var

2022-12-07 17:06 UTC, cyrheel commented on src/components/DisplayAll.jsx
> +        OPEN ALL
When open change this to "Close all"

2022-12-07 17:07 UTC, cyrheel commented on src/components/DisplayAll.jsx
> +            <Cards openAll={openAll} cardsData={val} key={val.ID} />
useless key param

2022-12-12 13:00 UTC, Dreyrk commented on src/Pages/Home.jsx
> +        <h5>{page === 0 ? null : page}</h5>
why not ?

2022-12-17 17:27 UTC, cyrheel requested changes

2022-12-17 17:27 UTC, cyrheel commented on src/App.js
>  import { Route, Routes } from "react-router-dom";
move all "router" related code to a router.js file

2022-12-17 17:27 UTC, cyrheel commented on src/App.js
> +      url: `/api/cards?page=${page}&limit=${limit !== 0 && limit}`,
If limit is equal to zero the request gonna be like "?page=0&limit=" notice the =nothing.  

Manage this to send only ?page=0 when you don't need limit

2022-12-17 17:27 UTC, cyrheel commented on src/App.js
> +      })
You can do this with one and only .then

2022-12-17 17:27 UTC, cyrheel commented on src/App.js
> +          </Routes>
Move "router" related code

2022-12-17 17:27 UTC, cyrheel commented on src/components/Cards.jsx
>    const filteredName = Name.replace(/\s*\(.*?\)\s*/g, "");
Move this regex to the  back-end

2022-12-17 17:27 UTC, cyrheel commented on src/components/Cards.jsx
> +  const filteredRarity = Rarity.substring(9);
You can also move this to back-end

2022-12-17 17:27 UTC, cyrheel commented on src/components/Cards.jsx
> +                </svg>
Maybe try to do a <SvgStar /> Component who return this svg tag so you can import it like any other component. it will clean code

2022-12-17 17:27 UTC, cyrheel commented on src/components/DeckModal.jsx
> +        </svg>
Same as other svg

2022-12-17 17:27 UTC, cyrheel commented on src/components/Header.jsx
>        </NavLink>
useNavigate

2022-12-17 17:27 UTC, cyrheel commented on src/components/PageNav.jsx
> +import React from "react";
Add a way to select a specific page

2022-12-17 17:27 UTC, cyrheel commented on src/components/PageNav.jsx
> +      {page < 228 ? (
Do not hardcode the number of page

2023-01-22 00:26 UTC, merged